### PR TITLE
chenged placement validation

### PR DESCRIPTION
**Pull request by jrosendahl**
Looks like we are checking for a placement array where it should be an int.  That is not awesome and should be fixed.

### CODE REVIEW

**Review by mikhalovich — APPROVED** [review]

**Comment by maximpakhomov** [comment]
@jrosendahl 
also, we have for Video Object:
the attribute `pos` with Integer Type
screenshot_7
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf#page=50&zoom=100,92,862
**Now:**
`'pos': (value) => Array.isArray(value) && value.every(v => v >= 0 && v <= 7),`

And the attribute `delivery` with Array Type
screenshot_8
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf#page=54&zoom=100,92,709
**Now:**
`'delivery': (value) => [1, 2, 3].indexOf(value) !== -1,`

Do we need to change types for `pos` and `delivery` too?

maybe something like this
`'pos': (value) => isInteger(value) && value >= 0 && value <= 7,`
`'delivery': (value) => Array.isArray(value) && value.every(v => v >= 1 && v <= 3),`

**Comment by jrosendahl** [comment]
@maximpakhomov that is great feedback thanks for the additional catches.

**Review by cpabst — APPROVED** [review]
Okey Doke.

**Review by cpabst — APPROVED** [review]
Still OK.

**Review by maximpakhomov — APPROVED** [review]

**Comment by maximpakhomov** [comment]
@jrosendahl @cpabst if this PR is no longer needed, can it be closed or merged?

**Comment by cpabst** [comment]
I'll defer to @jrosendahl on this one.

**Pull request closed without merging**
