### PR TITLE
feat: [EX-3265] format tests for prebid.js adapter

### PR DESCRIPTION
**Pull request by maximpakhomov**

### CODE REVIEW

**Review by cpabst — APPROVED** [review]
LGTM

**Comment by maximpakhomov** [comment]
@cpabst Can you create a PR in the Prebid.js repository from this branch?

**Comment by cpabst** [comment]
@maximpakhomov You bet. I'll do that this morning.

**Comment by maximpakhomov** [comment]
PR was merged to the prebid.js repo.

**Pull request closed without merging**
